services:
  allyapp:
    container_name: allyapp
    image: ghcr.io/ally-360/webpage-platform:latest
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - ally360-api_default

networks:
  ally360-api_default:
    external: true
